---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.11.1
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.34.3

nodeSubnetV4: 10.0.30.0/24
nodeSubnetV6: 2a0d:3344:245b:2702::/64

vip: 10.0.30.20
